### ISSUE TITLE
Invalid AOV type "emission"!

### ISSUE THREAD

**Issue by derrick-xwp** [diolatzis/active-exploration#1]
RuntimeError: ​[xml.cpp:1047] Error while loading "E:\MY_PROJECTS\active_extrapolation\active-exploration\scenes\bedroom\scene.xml" (near line 3, col 8): could not instantiate integrator plugin of type "aov": 
[xml.cpp:1047]   [AOVIntegrator] Invalid AOV type "emission"!

**Comment by derrick-xwp** [comment]
Is the official mitsuba2 compatable with your code? Because I see the scene.xml is quite different.

**Comment by diolatzis** [comment]
Hey, no you need to use the provided mitsuba 2 which is a custom version that includes many changes. One of them is additional aovs hence the error.

**Comment by derrick-xwp** [comment]
Hi, I see the link points to the official mitsuba 2. Where can I get the customized mitsuba2? Thanks

**Comment by diolatzis** [comment]
It is provided in the ext folder but it has the same compilation steps. I will make it more clear in the readme.

**Comment by derrick-xwp** [comment]
Oh, thanks..... I will compile again.  Several times of compilations today.....
