### ISSUE TITLE
Memory  consumption

### ISSUE THREAD

**Issue by derrick-xwp** [diolatzis/active-exploration#2]
Dear author,

How much GPU memory consumption on your side?

My desktop is with RTX2070 (8GB) and there is OOM when previewing.

Thanks

**Comment by diolatzis** [comment]
The scene specifications are given for running on a RTX 3090. To avoid OOM try reducing the resolution of the buffers or samples per pixel.

**Comment by diolatzis** [comment]
I'll close this issue as I updated the readme saying how to reduce memory usage. I might try to optimize this aspect of mitsuba rendering in the future.
