### ISSUE TITLE
descriptions

### ISSUE THREAD

**Issue by derrick-xwp** [diolatzis/active-exploration#3]
https://gitlab.inria.fr/fungraph/active-exploration/-/blob/master/neural_rendering/samplers/mcmc_sampler.py#L47

Dear author,

Can you give me more descriptions to the above function? such as the corresponding content in paper or other webpage.

Thanks!

**Comment by diolatzis** [comment]
Hi, sure thing.
The small step routine is from the original [Primary Sample Space paper from Kelemen et al.](https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-8659.t01-1-00703?casa_token=XcOCMBz25xEAAAAA:nwOtS8ovxoypFL4mHe0-fItphBdiFYUdGf9YkDKY_o8BnSnDr-DuhQsKcOIvcRB0UaaM2YxMscSV) which is also used in [Mitsuba](https://github.com/mitsuba-renderer/mitsuba/blob/cfeb7766e7a1513492451f35dc65b86409655a7b/src/integrators/pssmlt/pssmlt_sampler.h#L70). There are other ways to do small steps as well like [this](https://github.com/mitsuba-renderer/mitsuba/blob/cfeb7766e7a1513492451f35dc65b86409655a7b/src/integrators/pssmlt/pssmlt_sampler.h#L93) simpler version but we went with Kelemen's approach. I will update the code to clarify.
