### ISSUE TITLE
Subprocess crashed, retrying...

### ISSUE THREAD

**Issue by derrick-xwp** [diolatzis/active-exploration#4]
Dear authors,

I think some scenes are incomplete.

When I tried to train on veach-ajar, the Subprocess always crashed.

Do you know the reason? 

Thanks!

2022-06-27 14:46:05 INFO  main  [optix_api.cpp:56] Dynamic loading of the Optix library ..
Subprocess crashed, retrying...

**Comment by derrick-xwp** [comment]
After setting --num_patches  to a much smaller number solve the issue.

But still don't know the cause since the terminal outputs contain not much information.

But I think some scenes are still incomplete.

**Comment by diolatzis** [comment]
The parameter `--num_patches` controls the number of patches being rendered and number of markov chains during training. If that number is too high for the available graphics memory the subprocess will crash everytime. It's in my todo to  reduce GPU memory requirements. What do you mean by some scenes are incomplete and which ones?

**Comment by derrick-xwp** [comment]
Thanks!
