### ISSUE TITLE
Rendered output is better than GT

### ISSUE THREAD

**Issue by derrick-xwp** [diolatzis/active-exploration#5]
Dear author,

I have tested a trained model using preview_widget_varying.py

But I found that the GT rendered by renderer.get_custom_render is much worse than the rendered image from mode.

What could be the reason for this?

**Comment by derrick-xwp** [comment]
By the way, what is the difference between preview_widget_buffers.py and preview_widget_varying.py?

**Comment by derrick-xwp** [comment]
GT:
<img width="617" alt="截屏2022-06-29 下午11 09 36" src="https://user-images.githubusercontent.com/53371723/176471495-fee3249e-27ea-4110-9e53-a567be67180f.png">

PRED:
<img width="658" alt="图片" src="https://user-images.githubusercontent.com/53371723/176471526-83a75238-9997-4bff-b321-570874b94190.png">

**Comment by derrick-xwp** [comment]
Thanks!

**Comment by diolatzis** [comment]
Hey,

So the GT output is blurry cause you are using scene.xml which is the training scene config. If you use preview.xml you should get the high res ground truth. Preview widget buffers is mostly for debugging the scene variations when creating a new scene. It visualizes the auxiliary that will be fed to the network during training and it doesn't need a trained model.

**Comment by derrick-xwp** [comment]
May I ask the reason of using different xml files? such as preview_buffers and preview?

**Comment by derrick-xwp** [comment]
<img width="1186" alt="截屏2022-06-29 下午11 49 04" src="https://user-images.githubusercontent.com/53371723/176480271-79d4d919-0b0e-4922-8fff-544ebf6dcc1e.png">


Ok, now I get much better GT.
But we can see there is some noise pixels (shiny red) in GT, is this normal?   THanks!

**Comment by diolatzis** [comment]
> May I ask the reason of using different xml files? such as preview_buffers and preview?

Yes ofc, the reason is that the preview_buffers has only the auxiliary buffers integrator so it only renders using 1 bounce. The preview is used for the full global illumination image. For inference we only need the buffers and use preview_buffers and once you need a ground truth sample we use preview which takes way more time. 

>But we can see there is some noise pixels (shiny red) in GT, is this normal?

Yes you can increase the samples_per_pixel parameter in the preview xml for more converged results but you may run out of memory.

**Comment by derrick-xwp** [comment]
Thanks!
